[package]
name = "gct"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.19.2", features = ["full"] }
spin_sleep = "1.1.1"
tiny_http = "0.11.0"
crossbeam = "0.8.1"
ringbuf = "0.2.8"
fundsp = "0.6.4"
chrono = "0.4"

[dependencies.symphonia]
git = "https://github.com/FelixMcFelix/Symphonia"
features = ["mp3", "ogg", "wav", "pcm"]
branch = "songbird-fixes"
default-features = false

[dependencies.poise]
git = "https://github.com/GnomedDev/poise"
branch = "personal"

[dependencies.songbird]
git = "https://github.com/GnomedDev/songbird"
branch = "symphonia-personal"

[patch."https://github.com/serenity-rs/serenity"]
serenity = { git = "https://github.com/GnomedDev/serenity", branch = "personal" }

[patch.crates-io."serenity"]
git = "https://github.com/GnomedDev/serenity"
branch = "personal"